name: cubit_form
description: Cubit Form
version: 0.0.1
homepage: https://github.com/kherel/cubit_form

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  shortuuid: ^2.1.1
  bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0
flutter:
  uses-material-design: true
