name: cubit_form
description: Cubit Form
version: 2.0.5
homepage: https://github.com/kherel/cubit_form

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
